### ISSUE TITLE
It raise issue at the last iteration of epoch[0]

### ISSUE THREAD

**Issue by wenbohuang1002** [VinAIResearch/fsvc-ata#1]
I have followed the README.md to process the kinetics and somethingV2 dataset. When training on kinetics and somethingV2, It always raise issue at the last iteration of [0]. Issue on kinetics (the issue also appear in somethingV2) like the following have been showed. It seems to be have some problem with the transforms.Resize or Sampler.py. Can you tell me how to solve this? Thank you very much!

141it [00:49,  3.11it/s]Epoch: [0][140/199], lr: 0.00100	Time 0.322 (0.359)	Data 0.000 (0.010)	Loss 2.0342 (2.8352)	Prec@1 18.750 (7.358)	Prec@5 53.125 (23.426)	Mem 13531
161it [00:56,  3.10it/s]Epoch: [0][160/199], lr: 0.00100	Time 0.322 (0.355)	Data 0.000 (0.009)	Loss 1.8897 (2.7315)	Prec@1 9.375 (9.336)	Prec@5 53.125 (26.747)	Mem 13531
181it [01:02,  3.09it/s]Epoch: [0][180/199], lr: 0.00100	Time 0.325 (0.351)	Data 0.000 (0.008)	Loss 1.7050 (2.6349)	Prec@1 28.125 (10.912)	Prec@5 62.500 (29.523)	Mem 13531
199it [01:08,  2.90it/s]
0 batch [tensor([1015, 1064]), tensor([275, 292]), tensor([], dtype=torch.int64), tensor([], dtype=torch.int64), tensor([], dtype=torch.int64)]
Traceback (most recent call last):
  File "/home/wenbohuang/Projects/fsvc-ata-main/main.py", line 255, in <module>
    main()
  File "/home/wenbohuang/Projects/fsvc-ata-main/main.py", line 193, in main
    prec1 = inductive(val_loader, model, ata_helper, args, log)
  File "/home/wenbohuang/Projects/fsvc-ata-main/inference.py", line 29, in inductive
    for i, (input, _) in tqdm(enumerate(val_loader)):
  File "/home/wenbohuang/anaconda3/envs/hwb/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 444, in __iter__
    return self._get_iterator()
  File "/home/wenbohuang/anaconda3/envs/hwb/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 390, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/wenbohuang/anaconda3/envs/hwb/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1115, in __init__
    self._reset(loader, first_iter=True)
  File "/home/wenbohuang/anaconda3/envs/hwb/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1148, in _reset
    self._try_put_index()
  File "/home/wenbohuang/anaconda3/envs/hwb/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1382, in _try_put_index
    index = self._next_index()
  File "/home/wenbohuang/anaconda3/envs/hwb/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 671, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/wenbohuang/Projects/fsvc-ata-main/ops/samplers.py", line 33, in __iter__
    batch = torch.stack(batch).t().reshape(-1)
RuntimeError: stack expects each tensor to be equal size, but got [2] at entry 0 and [0] at entry 2

**Comment by khoiucd** [comment]
The error occurred during testing while it tried to sample few-shot episodes. In this function, the sampler first tries to sample 5 (self.n_cls) different classes:

https://github.com/VinAIResearch/fsvc-ata/blob/bf1cb7de864e64e402aa81f73672fcb8a198645c/ops/samplers.py#L24

Then for each class, it samples 2 (self.n_per) video indexes:

https://github.com/VinAIResearch/fsvc-ata/blob/bf1cb7de864e64e402aa81f73672fcb8a198645c/ops/samplers.py#L31

So the batch should have five elements, each has indexes of two videos. 

It seems that some videos are missing, and some classes have no videos. I suggest you check the list self.m_ind. It stores the indexes of all classes. 

https://github.com/VinAIResearch/fsvc-ata/blob/bf1cb7de864e64e402aa81f73672fcb8a198645c/ops/samplers.py#L31

If you still cannot detect the error, please send me your train.txt, test.txt, and val.txt files.

**Comment by wenbohuang1002** [comment]
Hi, Khoiucd! Thank you very much. I have modify the code then the code seems to run by a strange way. The results I achieved seems to have a large gap when compared with the results in your paper. It seems that some videos are missing. So I attempt to seed my train.txt, test.txt, and val.txt files of two datasets to your E-mail. I also post the link of .txt file in zip at [here](https://github.com/wenbohuang1002/wenbohuang1002.github.io/blob/main/annotations.zip)

I modify code in the line24 of smapler.py like:

    def __iter__(self):
        for i_batch in range(self.n_batch):
            batch = []
            classes = torch.randperm(len(self.m_ind))[: self.n_cls]
            global empty_size
            for c in classes:
                l = self.m_ind[c]
                # print(l.size())
                pos = torch.randperm(len(l))[: self.n_per]
                if l.size() == torch.Size([0]):
                    batch.append(torch.LongTensor(np.zeros((empty_size), dtype=np.int)))
                else:
                    batch.append(l[pos])
                    empty_size = l[pos].size()
                    # print(empty_size)
            # print(i_batch, "batch", batch)
            batch = torch.stack(batch).t().reshape(-1)
            yield batch

**Comment by khoiucd** [comment]
Hi,

I have read your annotation files. The label of each video in each file should start from 0. For example, if there are 24 categories in test set, then in the text.txt file, the labels should be in the set {0,1,2,...,23}. However, in your test.txt file, the labels are in {76,77,...,99}.

You need to generate the annotation files again using [ops/gen_label_sthv2.py](ops/gen_label_sthv2.py). And please keep the [samplers.py](https://github.com/VinAIResearch/fsvc-ata/blob/bf1cb7de864e64e402aa81f73672fcb8a198645c/ops/samplers.py#L31) file untouched.

**Comment by wenbohuang1002** [comment]
Yeah, thank you very much. I have also noticed the problem of labels. On smsmv2, I can re-produce your result ! However, I can't find related code about how to pre-process the kinetics dataset (with 10000 videos). Could give me a link of processing kinetics? Thank you again!!!!

**Comment by wenbohuang1002** [comment]
Following your advice, I have tried to process the label of the kinetics again and I will try again on kinetics. The issue have been solved! Thank you very much! 
By the way, now I am Ph.D student in Southeast University China. We can communicate more if possible! :-)

**Comment by khoiucd** [comment]
For the kinetics dataset, you just need to process it in the same manner (download videos, extract frames, generate annotations). 

And sure, I am open to discussing!
